[package]
name = "scrapper"
version = "0.1.0"
authors = ["Ruben Paz <me@ruben.io>"]
edition = "2018"

[dependencies]
reqwest = "0.9.10"
html5ever = "0.22.5"
log = "0.4.6"
env_logger = "0.6.0"
clap = "2.32.0"
